/**
 * Canonical facts about the site, used by metadata, structured data,
 * the sitemap and llms.txt so they can never drift apart.
 */

export const SITE_URL = 'https://keplix.co.in';

export const SITE_NAME = 'Keplix';

export const SITE_TAGLINE = 'Drive Smarter, Book Faster';

/**
 * Default share image: a purpose-built 1200×630 card. Generated by
 * scripts/make-og-image.mjs — regenerate it there rather than editing by hand,
 * so the copy and branding stay in one place. This replaced the square logo,
 * which every platform either letterboxed or cropped.
 */
export const DEFAULT_OG_IMAGE = `${SITE_URL}/og-image.png`;

export const DEFAULT_DESCRIPTION =
  'Compare prices from verified car workshops, book a service in minutes and track it in real time. Keplix connects car owners with trusted garages across India.';

/** The service categories the marketplace covers, used in Service schema and llms.txt. */
export const SERVICE_CATEGORIES = [
  'Car servicing and maintenance',
  'AC repair and gas refill',
  'Battery replacement',
  'Tyre replacement and wheel alignment',
  'Denting and painting',
  'Car wash and detailing',
  'Breakdown assistance',
  'Car accessories fitting',
] as const;

export const absoluteUrl = (path: string): string =>
  path.startsWith('http') ? path : `${SITE_URL}${path.startsWith('/') ? path : `/${path}`}`;
